version: '2'

services:
    reversi_sf_mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    reversi_sf_php:
      build: docker/php56fpm
      volumes:
        - .:/app
        - ./docker/php56fpm/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    reversi_sf_nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
         - .:/app
         - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
         - ./var/nginx/:/var/log/nginx
