services:

  # Facebook

  app.facebook.api:
    class: AppBundle\Facebook\FacebookApi
    arguments: [{}]

  app.facebook.controller:
    class: AppBundle\Facebook\FacebookController
    arguments: [ "@app.facebook.api", "@app.reversi.game_context.handler" ]

  app.facebook.context_action.subscriber:
        class: AppBundle\Facebook\FacebookContextActionSubscriber
        arguments: [ "@app.facebook.api", "@router" ]
        tags:
            - { name: kernel.event_subscriber }

  # Reversi

  app.reversi.controller:
    class: AppBundle\Reversi\ReversiController
    arguments: [ "@templating" ]

  app.reversi.game.manager:
    class: AppBundle\Reversi\GameManager
    arguments: [ "@doctrine.orm.default_entity_manager" ]

  app.reversi.game_context.handler:
    class: AppBundle\Reversi\GameContextHandler
    arguments: [ "@app.reversi.game.manager", "@app.reversi.ai", "@event_dispatcher" ]

  app.reversi.ai:
    class: AppBundle\Reversi\GameAi
    arguments: [ "@app.reversi.ai.http_client" ]

  app.reversi.ai.http_client:
    class: GuzzleHttp\Client
    arguments: [{"base_uri": "172.17.0.1:8080"}]
